const initialData = {
  tasks: {
    'task-1': { id: 'task-1', content: 'box-1', color: 'black'},
    'task-2': { id: 'task-2', content: 'box-2',  color: 'white'},
    'task-3': { id: 'task-3', content: 'box-3', color: 'black'},
    'task-4': { id: 'task-4', content: 'box-4', color: 'white'},
    'task-5': { id: 'task-5', content: 'box-5', color: 'black'},
    'task-6': { id: 'task-6', content: 'box-6', color: 'white'},
    'task-7': { id: 'task-7', content: 'box-7', color: 'black'},
    'task-8': { id: 'task-8', content: 'box-8', color: 'white'},
    'task-9': { id: 'task-9', content: 'box-9', color: 'white'},
    'task-10': { id: 'task-10', content: 'box-10', color: 'black'},
    'task-11': { id: 'task-11', content: 'box-11', color: 'white'},
    'task-12': { id: 'task-12', content: 'box-12', color: 'black'},
    'task-13': { id: 'task-13', content: 'box-13', color: 'white'},
    'task-14': { id: 'task-14', content: 'box-14', color: 'black'},
    'task-15': { id: 'task-15', content: 'box-15',color: 'white'},
    'task-16': { id: 'task-16', content: 'box-16', color: 'black'},
    'task-17': { id: 'task-17', content: 'box-17', color: 'black'},
    'task-18': { id: 'task-18', content: 'box-18', color: 'white'},
    'task-19': { id: 'task-19', content: 'box-19', color: 'black'},
    'task-20': { id: 'task-20', content: 'box-20', color: 'white'},
    'task-21': { id: 'task-21', content: 'box-21', color: 'black'},
    'task-22': { id: 'task-22', content: 'box-22', color: 'white'},
    'task-23': { id: 'task-23', content: 'box-23', color:'black'},
    'task-24': { id: 'task-24', content: 'box-24', color: 'white'},
    'task-25': { id: 'task-25', content: 'box-25', color: 'white'},
    'task-26': { id: 'task-26', content: 'box-26', color: 'black'},
    'task-27': { id: 'task-27', content: 'box-27', color: 'white'},
    'task-28': { id: 'task-28', content: 'box-28', color: 'black'},
    'task-29': { id: 'task-29', content: 'box-29', color: 'white'},
    'task-30': { id: 'task-30', content: 'box-30', color: 'black'},
    'task-31': { id: 'task-31', content: 'box-31', color: 'white'},
    'task-32': { id: 'task-32', content: 'box-18', color: 'black'},
    'task-33': { id: 'task-33', content: 'box-18', color: 'black'},
    'task-34': { id: 'task-34', content: 'box-18', color: 'white'},
    'task-35': { id: 'task-35', content: 'box-18', color: 'black'},
    'task-36': { id: 'task-36', content: 'box-18', color: 'white'},
    'task-37': { id: 'task-37', content: 'box-18', color: 'black'},
    'task-38': { id: 'task-38', content: 'box-18', color: 'white'},
    'task-39': { id: 'task-39', content: 'box-18', color: 'black'},
    'task-40': { id: 'task-40', content: 'box-18', color: 'white'},
    'task-41': { id: 'task-41', content: 'box-18', color: 'white'},
    'task-42': { id: 'task-42', content: 'box-19', color: 'black'},
    'task-43': { id: 'task-43', content: 'box-20', color: 'white'},
    'task-44': { id: 'task-44', content: 'box-21', color: 'black'},
    'task-45': { id: 'task-45', content: 'box-22', color: 'white'},
    'task-46': { id: 'task-46', content: 'Watch my  show', color: 'black'},
    'task-47': { id: 'task-47', content: 'Charge phone', color: 'white'},
    'task-48': { id: 'task-48', content: 'Cook nner', color: 'black'},
    'task-49': { id: 'task-49', content: 'Take out the garbage', color: 'black'},
    'task-50': { id: 'task-50', content: 'Watch my favourite show', color: 'white'},
    'task-51': { id: 'task-51', content: 'Charge my phone', color: 'black'},
    'task-52': { id: 'task-52', content: 'Cook dinner', color: 'white'},
    'task-53': { id: 'task-53', content: 'Take o', color: 'black'},
    'task-54': { id: 'task-54', content: 'Watch my  show', color: 'white'},
    'task-55': { id: 'task-55', content: 'Charge phone', color: 'black'},
    'task-56': { id: 'task-56', content: 'Cook nner', color: 'white'},
    'task-57': { id: 'task-57', content: 'Take out the garbage', color: 'white'},
    'task-58': { id: 'task-58', content: 'Watch my favourite show', color: 'black'},
    'task-59': { id: 'task-59', content: 'Charge my phone', color: 'white'},
    'task-60': { id: 'task-60', content: 'Cook dinner', color: 'black'},
    'task-61': { id: 'task-61', content: 'Take o', color: 'white'},
    'task-62': { id: 'task-62', content: 'Watch my  show', color: 'black'},
    'task-63': { id: 'task-63', content: 'Charge phone', color: 'white'},
    'task-64': { id: 'task-64', content: 'Cook nner', color: 'black'},
  },
  columns: {
    'column-1': {
      id: 'column-1',
      title: 'Todo',
      taskIds: ['task-1', 'task-2', 'task-3', 'task-4', 'task-5', 'task-6', 'task-7', 'task-8'],   
    }, 
    'column-2': {
      id: 'column-2',
      title: 'Todo',
      taskIds: ['task-9', 'task-10', 'task-11', 'task-12', 'task-13', 'task-14', 'task-15', 'task-16'], 
    }, 
    'column-3': {
      id: 'column-3',
      title: 'Todo',
      taskIds: ['task-17', 'task-18', 'task-19', 'task-20', 'task-21', 'task-22', 'task-23', 'task-24'],   
    }, 
    'column-4': {
      id: 'column-4',
      title: 'Todo',
      taskIds: ['task-25', 'task-26', 'task-27', 'task-28', 'task-29', 'task-30', 'task-31', 'task-32'],
    }, 
    'column-5': {
      id: 'column-5',
      title: 'Todo',
      taskIds: ['task-33', 'task-34', 'task-35', 'task-36', 'task-37', 'task-38', 'task-39', 'task-40'],   
      }, 
    'column-6': {
      id: 'column-6',
      title: 'Todo',
      taskIds: ['task-41', 'task-42', 'task-43', 'task-44', 'task-45', 'task-46', 'task-47', 'task-48'],   
    }, 
    'column-7': {
      id: 'column-7',
      title: 'Todo',
      taskIds: ['task-49', 'task-50', 'task-51', 'task-52', 'task-53', 'task-54', 'task-55', 'task-56'],   
    }, 
    'column-8': {
      id: 'column-8',
      title: 'Todo',
      taskIds: ['task-57', 'task-58', 'task-59', 'task-60', 'task-61', 'task-62', 'task-63', 'task-64'],   
    }, 
  },
  columnOrder: ['column-1', 'column-2', 'column-3', 'column-4', 'column-5', 'column-6', 'column-7', 'column-8'],
}
export default initialData;